name: CI Pipeline

on:
  push:
    branches:
      - master  # Указываем master, если это ваша основная ветка
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show OS info
        run: |
          echo "Hello from GitHub Actions!"
          cat /etc/os-release
